/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Begin OAuth flow */
        get: operations["authStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth redirect target; sets session cookie */
        get: operations["authCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear session */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/link/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link an additional SSO identity */
        post: operations["authLinkStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user, linked identities, and portfolio ID */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio overview (cash, positions, best-effort equity) */
        get: operations["getPortfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Order history (paginated) */
        get: operations["listOrders"];
        put?: never;
        /** Submit an order */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{id}/orders/{orderId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an order if cancellable */
        post: operations["cancelOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Equity over time from valuation snapshots (paginated) */
        get: operations["getPortfolioHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ranked rows from the latest snapshot */
        get: operations["getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest price_bar.close per symbol */
        get: operations["getQuotes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** S&P 500 universe (tradeable subset) */
        get: operations["getSymbols"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/universe/upsert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add or update S&P 500 membership rows */
        post: operations["adminUpsertUniverse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/universe/backfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manually re-trigger backfill for a symbol */
        post: operations["adminBackfillUniverse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/ops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operational view (snapshot lag, Finnhub rate limits, queue depth) */
        get: operations["adminGetOps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        OrderSide: "buy" | "sell";
        /** @enum {string} */
        OrderType: "market";
        /** @enum {string} */
        OrderStatus: "accepted" | "rejected" | "filled" | "cancelled";
        ApiError: {
            error: {
                /** @description Machine-readable error code, e.g. SYMBOL_NOT_TRADEABLE */
                code: string;
                /** @description Human-readable error message */
                message: string;
                /** @description Additional error context (implementation-defined) */
                details?: unknown;
            };
        };
        User: {
            /** Format: uuid */
            id: string;
            displayName: string;
            email: string | null;
            /** @enum {string} */
            role: "player" | "admin";
            /** Format: date-time */
            createdAt: string;
        };
        Identity: {
            /** @enum {string} */
            provider: "google" | "github";
            emailAtLink: string | null;
        };
        Portfolio: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            algoId: string | null;
            /**
             * Format: int64
             * @description Cents available
             */
            cash: number;
            /** Format: date-time */
            joinedAt: string;
        };
        Order: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            portfolioId: string;
            symbol: string;
            side: components["schemas"]["OrderSide"];
            type: components["schemas"]["OrderType"];
            /** @description Fractional shares (NUMERIC 20,8) */
            quantity: number;
            status: components["schemas"]["OrderStatus"];
            rejectReason: string | null;
            idempotencyKey: string;
            /** @enum {string} */
            source: "human" | "algo";
            /** Format: date-time */
            createdAt: string;
        };
        Fill: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderId: string;
            symbol: string;
            side: components["schemas"]["OrderSide"];
            /** @description Fractional shares (NUMERIC 20,8) */
            quantity: number;
            /**
             * Format: int64
             * @description Cents per share at fill
             */
            price: number;
            /** Format: date-time */
            filledAt: string;
        };
        ValuationSnapshot: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            portfolioId: string;
            /** Format: date-time */
            takenAt: string;
            /**
             * Format: int64
             * @description Cents
             */
            cash: number;
            /**
             * Format: int64
             * @description Cents (sum of qty × price)
             */
            positionsValue: number;
            /**
             * Format: int64
             * @description Cents (cash + positionsValue)
             */
            equity: number;
        };
        PositionView: {
            symbol: string;
            /** @description Fractional shares */
            quantity: number;
            /**
             * Format: int64
             * @description Cents per share (cost basis)
             */
            avgCost: number;
            /**
             * Format: int64
             * @description Latest price_bar.close in cents; null if not yet backfilled
             */
            lastPrice: number | null;
            /**
             * Format: int64
             * @description Cents (quantity × lastPrice); null if lastPrice is null
             */
            marketValue: number | null;
        };
        PortfolioView: {
            portfolio: components["schemas"]["Portfolio"];
            positions: components["schemas"]["PositionView"][];
            /**
             * Format: int64
             * @description Cents (cash + sum of marketValues); best-effort live
             */
            equity: number | null;
            /**
             * Format: int64
             * @description Cents; equals cash in v1 (no margin)
             */
            buyingPower: number;
            /**
             * Format: date-time
             * @description When the official ranking last refreshed
             */
            lastSnapshotAt: string | null;
        };
        MeResponse: {
            user: components["schemas"]["User"];
            identities: components["schemas"]["Identity"][];
            /**
             * Format: uuid
             * @description v1 — each user has exactly one portfolio
             */
            portfolioId: string;
        };
        CreateOrderRequest: {
            symbol: string;
            side: components["schemas"]["OrderSide"];
            type: components["schemas"]["OrderType"];
            /** @description Fractional shares; must be > 0 */
            quantity: number;
            /** @description Client-generated deduplication key */
            idempotencyKey: string;
        };
        CreateOrderResponse: {
            order: components["schemas"]["Order"];
            /** @description Present if immediately filled (v1 model) */
            fill: components["schemas"]["Fill"] | null;
        };
        OrdersPage: {
            items: components["schemas"]["Order"][];
            nextCursor: string | null;
        };
        HistoryPage: {
            items: components["schemas"]["ValuationSnapshot"][];
            nextCursor: string | null;
        };
        LeaderboardRowItem: {
            rank: number;
            /** Format: uuid */
            portfolioId: string;
            /** @description User display name; "index" for the bot */
            displayName: string;
            isBot: boolean;
            /**
             * Format: int64
             * @description Cents
             */
            equity: number;
            /** @description Return vs starting capital */
            returnPct: number;
        };
        LeaderboardResponse: {
            /**
             * Format: date-time
             * @description Snapshot this ranking reflects
             */
            takenAt: string;
            rows: components["schemas"]["LeaderboardRowItem"][];
            nextCursor: string | null;
        };
        QuoteEntry: {
            /**
             * Format: int64
             * @description Latest price_bar.close in cents
             */
            price: number | null;
            /**
             * Format: date-time
             * @description Timestamp of the price bar
             */
            ts: string | null;
        };
        QuotesResponse: {
            /**
             * Format: date-time
             * @description Latest price_bar timestamp considered
             */
            asOf: string;
            /** @description Symbol → QuoteEntry map */
            quotes: {
                [key: string]: components["schemas"]["QuoteEntry"];
            };
        };
        SymbolItem: {
            symbol: string;
            /** @description false → not yet tradeable */
            backfilled: boolean;
        };
        SymbolsResponse: {
            items: components["schemas"]["SymbolItem"][];
        };
        UpsertUniverseRequest: {
            /** @description S&P 500 symbols to add or update */
            symbols: string[];
        };
        BackfillRequest: {
            /** @description Symbol to re-trigger backfill for */
            symbol: string;
        };
        OpsResponse: {
            /** Format: date-time */
            lastSnapshotAt: string | null;
            /** Format: int64 */
            snapshotLagSec: number | null;
            finnhubRest429sLast24h: number;
            jobQueueDepth: number;
            /** @description Count of universe_symbol where backfilled = false */
            backfillRemaining: number;
        };
    };
    responses: {
        /** @description Unauthenticated */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Validation error */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Rate limited */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        portfolioId: string;
        orderId: string;
        provider: "google" | "github";
        limitParam: number;
        cursorParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authStart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["parameters"]["provider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to provider */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    authCallback: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path: {
                provider: components["parameters"]["provider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to app */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    authLinkStart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["parameters"]["provider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to provider */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["portfolioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Portfolio view */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioView"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listOrders: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limitParam"];
                cursor?: components["parameters"]["cursorParam"];
            };
            header?: never;
            path: {
                id: components["parameters"]["portfolioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated order list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdersPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["portfolioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Order created and filled (v1) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrderResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Idempotency key conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["portfolioId"];
                orderId: components["parameters"]["orderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getPortfolioHistory: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limitParam"];
                cursor?: components["parameters"]["cursorParam"];
            };
            header?: never;
            path: {
                id: components["parameters"]["portfolioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated valuation snapshot list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getLeaderboard: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limitParam"];
                cursor?: components["parameters"]["cursorParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaderboard */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getQuotes: {
        parameters: {
            query: {
                /** @description Comma-separated symbols, e.g. AAPL,MSFT */
                symbols: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quotes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getSymbols: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Symbols */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolsResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    adminUpsertUniverse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertUniverseRequest"];
            };
        };
        responses: {
            /** @description Upserted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    adminBackfillUniverse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackfillRequest"];
            };
        };
        responses: {
            /** @description Backfill enqueued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    adminGetOps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ops status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
