/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Begin OAuth flow */
        get: operations["authStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth redirect target; sets session cookie */
        get: operations["authCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear session */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/link/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link an additional SSO identity */
        post: operations["authLinkStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user, linked identities, and CSRF token */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The corpus of symbols with backfill state and bar-coverage bounds */
        get: operations["getUniverse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/symbols/{symbol}/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company logo image (downloaded from Massive into symbol_branding) */
        get: operations["getSymbolLogo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/symbols/{symbol}/icon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company icon image (downloaded from Massive into symbol_branding) */
        get: operations["getSymbolIcon"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pricing history for a corpus, from price_bar */
        get: operations["getPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate the returns of a series of orders, replayed against history */
        post: operations["evaluate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etfs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List defined ETFs */
        get: operations["listEtfs"];
        put?: never;
        /** Define a new ETF from a weighted set of universe symbols */
        post: operations["createEtf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etfs/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ETF key, e.g. "big7" */
                key: string;
            };
            cookie?: never;
        };
        /** Get ETF detail including normalized weights */
        get: operations["getEtf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etfs/{key}/returns": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        /** Total return % of the ETF over a window */
        get: operations["getEtfReturns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/sma-crossover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Backtest the built-in SMA-crossover strategy on an ETF */
        post: operations["runSmaStrategy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/universe/upsert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add or update corpus membership rows */
        post: operations["adminUpsertUniverse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/universe/backfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manually re-trigger backfill for a symbol */
        post: operations["adminBackfillUniverse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/ops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operational view (EOD-update lag, market data 429s, queue depth, backfill remaining) */
        get: operations["adminOps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        OrderSide: "buy" | "sell";
        ApiError: {
            error: {
                /** @description Machine-readable error code, e.g. SYMBOL_NOT_TRADEABLE */
                code: string;
                /** @description Human-readable error message */
                message: string;
                /** @description Additional error context (implementation-defined) */
                details?: unknown;
            };
        };
        User: {
            /** Format: uuid */
            id: string;
            displayName: string;
            email: string | null;
            /** @enum {string} */
            role: "player" | "admin";
            /** Format: date-time */
            createdAt: string;
        };
        Identity: {
            /** @enum {string} */
            provider: "google" | "github";
            emailAtLink: string | null;
        };
        MeResponse: {
            user: components["schemas"]["User"];
            identities: components["schemas"]["Identity"][];
            /** @description Rotating token required in X-CSRF-Token on state-changing requests */
            csrfToken: string;
            /** @description Fantasy Street leagues the user is a member of, for client routing */
            leagues: components["schemas"]["LeagueMembership"][];
        };
        UniverseItem: {
            symbol: string;
            /** @description false → no price history yet */
            backfilled: boolean;
            /** Format: date-time */
            backfilledAt: string | null;
            /**
             * Format: date-time
             * @description Earliest price_bar.ts for the symbol
             */
            firstBarAt: string | null;
            /**
             * Format: date-time
             * @description Latest price_bar.ts for the symbol
             */
            lastBarAt: string | null;
        };
        UniverseResponse: {
            items: components["schemas"]["UniverseItem"][];
        };
        PriceBar: {
            /**
             * Format: date-time
             * @description Bar date (UTC)
             */
            ts: string;
            /**
             * Format: int64
             * @description Cents
             */
            open: number;
            /**
             * Format: int64
             * @description Cents
             */
            high: number;
            /**
             * Format: int64
             * @description Cents
             */
            low: number;
            /**
             * Format: int64
             * @description Cents
             */
            close: number;
            volume: number | null;
        };
        PricesResponse: {
            /**
             * Format: date-time
             * @description Resolved window start
             */
            from: string;
            /**
             * Format: date-time
             * @description Resolved window end
             */
            to: string;
            /** @description Symbol → ordered bars within the window */
            series: {
                [key: string]: components["schemas"]["PriceBar"][];
            };
            /** @description Requested symbols not in universe / with no bars */
            missing: string[];
        };
        EvaluateOrder: {
            symbol: string;
            side: components["schemas"]["OrderSide"];
            /** @description Fractional shares (NUMERIC 20,8); must be > 0 */
            quantity: number;
            /**
             * Format: date-time
             * @description ISO-8601 — when this order executes
             */
            at: string;
        };
        EvaluateRequest: {
            /**
             * Format: int64
             * @description Cents
             */
            startingCash: number;
            orders: components["schemas"]["EvaluateOrder"][];
        };
        EvaluatedOrder: {
            symbol: string;
            side: components["schemas"]["OrderSide"];
            quantity: number;
            /** Format: date-time */
            at: string;
            /**
             * Format: int64
             * @description Cents/share at-or-before `at`; null if rejected
             */
            fillPrice: number | null;
            /** @enum {string} */
            status: "filled" | "rejected";
            /** @description SYMBOL_NOT_TRADEABLE | STALE_PRICE | INSUFFICIENT_FUNDS | INSUFFICIENT_POSITION */
            rejectReason: string | null;
        };
        FinalPosition: {
            symbol: string;
            quantity: number;
            /**
             * Format: int64
             * @description Cents per share (cost basis)
             */
            avgCost: number;
        };
        EquityPoint: {
            /** Format: date-time */
            ts: string;
            /**
             * Format: int64
             * @description Cents
             */
            equity: number;
        };
        EvaluateResponse: {
            orders: components["schemas"]["EvaluatedOrder"][];
            /**
             * Format: int64
             * @description Cents
             */
            finalCash: number;
            finalPositions: components["schemas"]["FinalPosition"][];
            /**
             * Format: int64
             * @description Cents (finalCash + Σ qty × last close)
             */
            finalEquity: number | null;
            /** @description Return vs startingCash */
            totalReturnPct: number | null;
            equityCurve: components["schemas"]["EquityPoint"][];
        };
        EtfWeight: {
            symbol: string;
            /** @description Normalized weight (sums to 1.0 across all members) */
            weight: number;
        };
        Etf: {
            /** Format: uuid */
            id: string;
            /** @description Stable handle, e.g. "big7" (referenced as "etf:big7" in /prices and /evaluate) */
            key: string;
            name: string;
            /**
             * Format: int64
             * @description Index level (cents) at baseDate — synthetic series is normalized to this
             */
            baseValue: number;
            /**
             * Format: date
             * @description t0 the series is rebased to
             */
            baseDate: string;
            /** Format: date-time */
            createdAt: string;
            /** @description Normalized weights (sum to 1.0) */
            weights: components["schemas"]["EtfWeight"][];
        };
        EtfSummary: {
            /** Format: uuid */
            id: string;
            key: string;
            name: string;
            memberCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        CreateEtfRequest: {
            /** @description Stable handle, e.g. "big7" */
            key: string;
            name: string;
            /**
             * Format: date
             * @description t0 for normalization (defaults to earliest common bar date)
             */
            baseDate?: string;
            /**
             * Format: int64
             * @description Cents; index level at baseDate (default 10000 = $100.00)
             */
            baseValue?: number;
            /** @description symbol → positive weight (need not sum to 1; normalized at compute time) */
            weights: {
                [key: string]: number;
            };
        };
        EtfListResponse: {
            items: components["schemas"]["EtfSummary"][];
        };
        EtfReturnsResponse: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            /** @description Total return % of the ETF over the window; null if no bars in window */
            returnPct: number | null;
        };
        SmaStrategyRequest: {
            /** @description ETF key to backtest (e.g. "sp500") */
            etfKey: string;
            /** @description Short SMA window in daily closes (default 20) */
            shortWindow?: number;
            /** @description Long SMA window in daily closes (default 50) */
            longWindow?: number;
            /**
             * Format: int64
             * @description Cents; starting cash for the backtest (default 1000000 = $10,000)
             */
            startingCash?: number;
            /** @description ISO date/datetime; window start (default full series) */
            from?: string;
            /** @description ISO date/datetime; window end (default now) */
            to?: string;
        };
        StrategyLeg: {
            /** @description Dense daily equity (cents) over the window */
            equityCurve: components["schemas"]["EquityPoint"][];
            /** @description Total return % vs startingCash; null if no data */
            totalReturnPct: number | null;
            /** @description Largest peak-to-trough drawdown as a positive %; null if no data */
            maxDrawdownPct: number | null;
        };
        StrategyBacktestResponse: {
            etfKey: string;
            shortWindow: number;
            longWindow: number;
            /** Format: int64 */
            startingCash: number;
            from: string;
            to: string;
            strategy: components["schemas"]["StrategyLeg"];
            /** @description Buy-and-hold baseline of the same ETF over the window */
            buyHold: components["schemas"]["StrategyLeg"];
            /** @description Faithful point-in-time fills from replaying the order series through /evaluate */
            orders: components["schemas"]["EvaluatedOrder"][];
        };
        UpsertUniverseRequest: {
            /** @description Symbols to add or update in the corpus */
            symbols: string[];
        };
        BackfillRequest: {
            /** @description Symbol to re-trigger backfill for */
            symbol: string;
        };
        OpsResponse: {
            /** @description ISO timestamp of the last successful EOD price-update run; null if none yet */
            lastEodUpdateAt: string | null;
            /** @description Seconds since the last EOD update (now - lastEodUpdateAt) */
            eodUpdateLagSec: number | null;
            marketData429sLast24h: {
                /** @description Massive 429 count in the trailing 24h */
                massive: number;
            };
            /** @description Currently-held worker job locks (backfill / session-update) */
            jobQueueDepth: number;
            /** @description Count of universe_symbol rows with backfilled = false */
            backfillRemaining: number;
        };
        /** @description Slot layout for a league's weekly lineup plus bench depth */
        RosterConfig: {
            /** @description Named starting slots (Anchor, Growth, Momentum, Value, Defense, Wildcard) */
            slots: string[];
            /** @description Number of bench slots (0–4) */
            bench: number;
        };
        LeagueMember: {
            userId: string;
            displayName: string;
            teamName: string | null;
            /** @enum {string} */
            role: "commissioner" | "manager";
            /** Format: date-time */
            joinedAt: string;
        };
        LeagueView: {
            id: string;
            name: string;
            commissionerUserId: string;
            /** @description Max managers (4–12) */
            size: number;
            seasonLengthWeeks: number;
            rosterConfig: components["schemas"]["RosterConfig"];
            /** @enum {string} */
            joinPolicy: "invite" | "open";
            /** @enum {string} */
            status: "forming" | "drafting" | "active" | "playoffs" | "archived";
            /** Format: date-time */
            createdAt: string;
            members: components["schemas"]["LeagueMember"][];
            /** @description size − current member count */
            openSlots: number;
        };
        LeagueSummary: {
            id: string;
            name: string;
            size: number;
            seasonLengthWeeks: number;
            /** @enum {string} */
            joinPolicy: "invite" | "open";
            /** @enum {string} */
            status: "forming" | "drafting" | "active" | "playoffs" | "archived";
            memberCount: number;
            openSlots: number;
            /** Format: date-time */
            createdAt: string;
        };
        LeagueListResponse: {
            items: components["schemas"]["LeagueSummary"][];
            total: number;
            limit: number;
            offset: number;
        };
        /** @description A user's membership in a league, as surfaced on /me */
        LeagueMembership: {
            leagueId: string;
            teamName: string | null;
            /** @enum {string} */
            role: "commissioner" | "manager";
            /** @enum {string} */
            status: "forming" | "drafting" | "active" | "playoffs" | "archived";
        };
        Invite: {
            token: string;
            leagueId: string;
            /** Format: date-time */
            expiresAt: string | null;
            maxUses: number | null;
            uses: number;
            /** Format: date-time */
            createdAt: string;
        };
        CreateLeagueRequest: {
            name: string;
            /** @description 4–12 */
            size: number;
            seasonLengthWeeks: number;
            rosterConfig?: components["schemas"]["RosterConfig"];
            /** @enum {string} */
            joinPolicy: "invite" | "open";
        };
        /** @description Commissioner settings edit; allowed only while status = forming */
        UpdateLeagueRequest: {
            name?: string;
            size?: number;
            seasonLengthWeeks?: number;
            rosterConfig?: components["schemas"]["RosterConfig"];
            /** @enum {string} */
            joinPolicy?: "invite" | "open";
        };
        CreateInviteRequest: {
            /** @description Invite lifetime in hours; omit for no expiry */
            expiresInHours?: number;
            /** @description Cap on accepted joins; omit for unlimited until expiry */
            maxUses?: number;
        };
        JoinLeagueRequest: {
            /** @description Invite token; required for invite-only leagues, optional for open leagues */
            token?: string;
        };
        /**
         * @description A draftable slot family a stock can qualify for
         * @enum {string}
         */
        PlayerGroup: "anchor" | "growth" | "momentum" | "value" | "defense" | "wildcard";
        /** @description Price-derived metrics behind a stock's group eligibility */
        PlayerMetrics: {
            /** @description Trailing ~3-month price return, percent */
            ret3mPct: number | null;
            /** @description Trailing ~12-month price return, percent */
            ret12mPct: number | null;
            /** @description Stddev of trailing daily returns (~90d), as a fraction */
            sigma: number | null;
            /** @description Mean daily volume over the window; null when unavailable */
            avgVolume: number | null;
        };
        /** @description Per-league ownership status for a stock */
        PlayerOwnership: {
            owned: boolean;
            /** @description Team name of the owning manager, when owned */
            ownerTeam?: string | null;
            /** @description Whether the owner holds it as a short (defense), when owned */
            isShort?: boolean | null;
        };
        PlayerInventoryItem: {
            symbol: string;
            groups: components["schemas"]["PlayerGroup"][];
            /** @description Trailing ~3-month return, surfaced for scouting */
            recentReturnPct: number | null;
            ownership: components["schemas"]["PlayerOwnership"];
        };
        PlayerListResponse: {
            items: components["schemas"]["PlayerInventoryItem"][];
            total: number;
            limit: number;
            offset: number;
        };
        PlayerDetail: {
            symbol: string;
            groups: components["schemas"]["PlayerGroup"][];
            /** @description Roster slot names this stock may fill */
            eligibleSlots: string[];
            recentReturnPct: number | null;
            metrics: components["schemas"]["PlayerMetrics"];
            ownership: components["schemas"]["PlayerOwnership"];
            /** @description Price-history window (~1y) for the detail chart */
            prices: components["schemas"]["PriceBar"][];
        };
        /**
         * @description Lifecycle of a league's snake draft
         * @enum {string}
         */
        DraftStatus: "scheduled" | "in_progress" | "complete";
        /** @description One landed pick in the snake order; the immutable draft log */
        DraftPick: {
            /** @description 1-based position in the overall snake order */
            overallPick: number;
            /** @description 1-based draft round */
            round: number;
            userId: string;
            symbol: string;
            /** @description Drafted as a short (Defense), scored as the inverse return */
            isShort: boolean;
            /** @description True when the pick clock expired and auto-draft chose it */
            auto: boolean;
            /** Format: date-time */
            pickedAt: string;
        };
        /** @description A seat in the snake order, present whether or not it is filled */
        DraftSlot: {
            overallPick: number;
            round: number;
            /** @description Manager on the clock for this position */
            userId: string;
        };
        /** @description The live draft board — order, picks so far, and the clock */
        DraftState: {
            id: string;
            leagueId: string;
            status: components["schemas"]["DraftStatus"];
            pickSeconds: number;
            /** @description slots + bench; every manager makes this many picks */
            totalRounds: number;
            /** @description size × totalRounds; the length of the snake order */
            totalPicks: number;
            /** @description Position on the clock; exceeds totalPicks once complete */
            currentOverallPick: number;
            /** @description Manager currently on the clock; null when complete */
            onClockUserId: string | null;
            /**
             * Format: date-time
             * @description When the current pick expires; null when not in progress
             */
            deadline: string | null;
            /** @description The full snake order, one seat per overall pick */
            order: components["schemas"]["DraftSlot"][];
            picks: components["schemas"]["DraftPick"][];
        };
        MakePickRequest: {
            symbol: string;
            /**
             * @description Draft the stock as a short into the Defense slot
             * @default false
             */
            isShort: boolean;
        };
        /** @description One filled slot in a weekly lineup */
        LineupSlot: {
            /** @enum {string} */
            slot: "anchor" | "growth" | "momentum" | "value" | "defense" | "wildcard" | "bench";
            /** @description Disambiguates repeated slots (bench, duplicate slots) */
            slotIndex: number;
            symbol: string;
            /** @description True for a Defense short; false for every long slot */
            isShort: boolean;
        };
        /** @description A manager's weekly starting lineup and its lock state */
        Lineup: {
            leagueId: string;
            userId: string;
            season: number;
            week: number;
            /** @description True once the scoring week's market open froze the lineup */
            locked: boolean;
            /** Format: date-time */
            lockedAt: string | null;
            /** @description True when the lock job auto-filled one or more slots */
            autoFilled: boolean;
            slots: components["schemas"]["LineupSlot"][];
        };
        SetLineupSlot: {
            /** @enum {string} */
            slot: "anchor" | "growth" | "momentum" | "value" | "defense" | "wildcard" | "bench";
            /**
             * @description Position within a repeated slot; defaults to 0
             * @default 0
             */
            slotIndex: number;
            symbol: string;
        };
        SetLineupRequest: {
            week: number;
            /** @default 1 */
            season: number;
            slots: components["schemas"]["SetLineupSlot"][];
        };
        /** @description One started slot's contribution to a manager's weekly score */
        ScoreBreakdownItem: {
            /** @enum {string} */
            slot: "anchor" | "growth" | "momentum" | "value" | "defense" | "wildcard" | "bench";
            symbol: string;
            /** @description True for a Defense short (scored as −r×10) */
            isShort: boolean;
            /** @description Prior-Friday close in cents, or null if no bar resolved */
            lastClose: number | null;
            /** @description This-Friday (or as-of) close in cents, or null */
            thisClose: number | null;
            /** @description Week percent return, or null when a close was missing */
            returnPct: number | null;
            /** @description Slot points (r×10 long, −r×10 short), rounded to 2 dp */
            points: number;
        };
        /** @description A manager's weekly point total and its per-slot breakdown */
        WeeklyScore: {
            leagueId: string;
            userId: string;
            season: number;
            week: number;
            /** @description Uncapped sum of started slots (losses included) */
            totalPoints: number;
            /** Format: date-time */
            computedAt: string;
            /** @description True for an in-week live total; false once Friday-settled */
            provisional: boolean;
            breakdown: components["schemas"]["ScoreBreakdownItem"][];
        };
        /** @description Every manager's settled score for one league week */
        LeagueScoresResponse: {
            season: number;
            week: number;
            scores: components["schemas"]["WeeklyScore"][];
        };
    };
    responses: {
        /** @description Unauthenticated */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Validation error */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        provider: "google" | "github";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authStart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["parameters"]["provider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to provider */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    authCallback: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path: {
                provider: components["parameters"]["provider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to app */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    authLinkStart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["parameters"]["provider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to provider */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getUniverse: {
        parameters: {
            query?: {
                /** @description When true, only symbols with price history */
                backfilled?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Universe */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getSymbolLogo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Universe symbol, e.g. AAPL or BRK-B (case-insensitive) */
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The logo image bytes (SVG/PNG; see Content-Type) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/svg+xml": string;
                    "image/png": string;
                };
            };
            /** @description Not modified (matched If-None-Match) */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getSymbolIcon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Universe symbol, e.g. AAPL or BRK-B (case-insensitive) */
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The icon image bytes (PNG/JPEG; see Content-Type) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                    "image/jpeg": string;
                };
            };
            /** @description Not modified (matched If-None-Match) */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPrices: {
        parameters: {
            query: {
                /** @description Comma-separated symbols, e.g. AAPL,MSFT (≤ 100) */
                symbols: string;
                /** @description ISO date/datetime; window start (default to − 2y) */
                from?: string;
                /** @description ISO date/datetime; window end (default now) */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Price history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    evaluate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluateRequest"];
            };
        };
        responses: {
            /** @description Evaluation result (stateless; nothing persisted) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluateResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listEtfs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ETF list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtfListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createEtf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEtfRequest"];
            };
        };
        responses: {
            /** @description ETF created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Etf"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getEtf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ETF key, e.g. "big7" */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ETF detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Etf"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getEtfReturns: {
        parameters: {
            query?: {
                /** @description ISO date/datetime; window start */
                from?: string;
                /** @description ISO date/datetime; window end (default now) */
                to?: string;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ETF return over the window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtfReturnsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    runSmaStrategy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmaStrategyRequest"];
            };
        };
        responses: {
            /** @description Backtest result with strategy and buy-and-hold equity curves */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyBacktestResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    adminUpsertUniverse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertUniverseRequest"];
            };
        };
        responses: {
            /** @description Upserted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    adminBackfillUniverse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackfillRequest"];
            };
        };
        responses: {
            /** @description Backfill flag reset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    adminOps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Platform health snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
