/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v2/aggs/ticker/{stocksTicker}/range/{multiplier}/{timespan}/{from}/{to}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Custom Bars (OHLC)
     * @description Retrieve aggregated historical OHLC (Open, High, Low, Close) and volume data for a specified stock ticker over a custom date range and time interval in Eastern Time (ET). Aggregates are constructed exclusively from qualifying trades that meet specific conditions. If no eligible trades occur within a given timeframe, no aggregate bar is produced. Covers pre-market, regular market, and after-hours sessions.
     */
    get: operations['getAggregates'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AggregateBar: {
      /**
       * Format: double
       * @description The close price for the symbol in the given time period.
       */
      c: number;
      /**
       * Format: double
       * @description The highest price for the symbol in the given time period.
       */
      h: number;
      /**
       * Format: double
       * @description The lowest price for the symbol in the given time period.
       */
      l: number;
      /** @description The number of transactions in the aggregate window. */
      n?: number;
      /**
       * Format: double
       * @description The open price for the symbol in the given time period.
       */
      o: number;
      /** @description Whether or not this aggregate is for an OTC ticker. Omitted when false. */
      otc?: boolean;
      /**
       * Format: int64
       * @description The Unix millisecond timestamp for the start of the aggregate window.
       */
      t: number;
      /**
       * Format: double
       * @description The trading volume of the symbol in the given time period.
       */
      v: number;
      /**
       * Format: double
       * @description The volume weighted average price.
       */
      vw?: number;
    };
    AggregatesResponse: {
      /** @description The exchange symbol that this item is traded under. */
      ticker: string;
      /** @description Whether or not this response was adjusted for splits. */
      adjusted?: boolean;
      /** @description The number of aggregates (minute or day) used to generate the response. */
      queryCount: number;
      /** @description A request id assigned by the server. */
      request_id?: string;
      /** @description The total number of results for this request. */
      resultsCount: number;
      /** @description The status of this request's response. */
      status: string;
      /** @description An array of aggregate bars for the requested ticker and time range. */
      results: components['schemas']['AggregateBar'][];
      /**
       * Format: uri
       * @description If present, this value can be used to fetch the next page of data.
       */
      next_url?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getAggregates: {
    parameters: {
      query?: {
        /** @description Whether or not the results are adjusted for splits. By default, results are adjusted. Set this to false to get results that are NOT adjusted for splits. */
        adjusted?: boolean;
        /** @description Sort the results by timestamp. asc returns results in ascending order (oldest first), desc returns results in descending order (newest first). */
        sort?: 'asc' | 'desc';
        /** @description Limits the number of base aggregates queried to create the aggregate results. Max 50000 and Default 5000. */
        limit?: number;
      };
      header?: never;
      path: {
        /** @description A case-sensitive ticker symbol. For example, AAPL represents Apple Inc. */
        stocksTicker: string;
        /** @description The size of the timespan multiplier. */
        multiplier: number;
        /** @description The size of the time window. Common values: minute, hour, day, week, month, quarter, year. */
        timespan:
          | 'second'
          | 'minute'
          | 'hour'
          | 'day'
          | 'week'
          | 'month'
          | 'quarter'
          | 'year';
        /** @description The start of the aggregate time window. Either a date with the format YYYY-MM-DD or a millisecond timestamp. */
        from: string;
        /** @description The end of the aggregate time window. Either a date with the format YYYY-MM-DD or a millisecond timestamp. */
        to: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful operation. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "adjusted": true,
           *       "next_url": "https://api.massive.com/v2/aggs/ticker/AAPL/range/1/day/1578114000000/2020-01-10?cursor=bGltaXQ9MiZzb3J0PWFzYw",
           *       "queryCount": 2,
           *       "request_id": "6a7e466379af0a71039d60cc78e72282",
           *       "results": [
           *         {
           *           "c": 75.0875,
           *           "h": 75.15,
           *           "l": 73.7975,
           *           "n": 1,
           *           "o": 74.06,
           *           "t": 1577941200000,
           *           "v": 135647456,
           *           "vw": 74.6099
           *         },
           *         {
           *           "c": 74.3575,
           *           "h": 75.145,
           *           "l": 74.125,
           *           "n": 1,
           *           "o": 74.2875,
           *           "t": 1578027600000,
           *           "v": 146535512,
           *           "vw": 74.7026
           *         }
           *       ],
           *       "resultsCount": 2,
           *       "status": "OK",
           *       "ticker": "AAPL"
           *     }
           */
          'application/json': components['schemas']['AggregatesResponse'];
        };
      };
    };
  };
}
