/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/stock/candle': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Stock Candles
     * @description Get OHLCV data for stocks. The endpoint returns historical data suitable for chart display. Resolution D+ requires a Finnhub paid plan for some markets.
     */
    get: operations['stockCandles'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/quote': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Global Stocks, Forex, Crypto price
     * Quote
     * @description <p>Get real-time quote data for US stocks. Constant polling is not recommended. Use websocket if you need real-time updates.</p><p>Real-time stock prices for international markets are supported for Enterprise clients via our partner's feed. <a href="mailto:support@finnhub.io">Contact Us</a> to learn more.</p>
     * @example {
     *       "url": "/quote?symbol=AAPL&token=<token>",
     *       "text": "/quote?symbol=AAPL"
     *     }
     * @example {
     *       "url": "/quote?symbol=MSFT&token=<token>",
     *       "text": "/quote?symbol=MSFT"
     *     }
     */
    get: operations['quote'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Candles: {
      /** @description List of open prices for returned candles */
      o?: number[];
      /** @description List of high prices for returned candles */
      h?: number[];
      /** @description List of low prices for returned candles */
      l?: number[];
      /** @description List of close prices for returned candles */
      c?: number[];
      /** @description List of volume data for returned candles */
      v?: number[];
      /** @description List of UNIX timestamps for returned candles */
      t?: number[];
      /**
       * @description Status of the response. This field can either be "ok" or "no_data".
       * @enum {string}
       */
      s?: 'ok' | 'no_data';
    };
    Quote: {
      /**
       * Format: float
       * @description Open price of the day
       */
      o?: number;
      /**
       * Format: float
       * @description High price of the day
       */
      h?: number;
      /**
       * Format: float
       * @description Low price of the day
       */
      l?: number;
      /**
       * Format: float
       * @description Current price
       */
      c?: number;
      /**
       * Format: float
       * @description Previous close price
       */
      pc?: number;
      /**
       * Format: float
       * @description Change
       */
      d?: number;
      /**
       * Format: float
       * @description Percent change
       */
      dp?: number;
      /**
       * Format: int64
       * @description UNIX timestamp
       */
      t?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  stockCandles: {
    parameters: {
      query: {
        /** @description Symbol */
        symbol: string;
        /** @description Supported resolution includes 1, 5, 15, 30, 60, D, W, M. Some timeframes might not be available depending on the exchange. */
        resolution: '1' | '5' | '15' | '30' | '60' | 'D' | 'W' | 'M';
        /** @description UNIX timestamp. Interval initial value. */
        from: number;
        /** @description UNIX timestamp. Interval end value. */
        to: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Candles'];
        };
      };
    };
  };
  quote: {
    parameters: {
      query: {
        /** @description Symbol */
        symbol: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Quote'];
        };
      };
    };
  };
}
