/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/quote': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Quote
     * @description Real-time quote data for US stocks. tickr uses this to capture each session's official close early: after the 16:00-ET close, `c` (current price) settles to the official regular-session close and does NOT drift with after-hours (empirically verified — value frozen across repeated post-close polls), which is the property the early weekly-close capture (TODO/30) relies on. Day OHLC (`o`/`h`/`l`), previous close (`pc`), and a quote timestamp (`t`) are also returned. Constant polling is discouraged by Finnhub; tickr polls once per symbol per post-close run under a token bucket.
     */
    get: operations['quote'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Quote: {
      /**
       * Format: float
       * @description Open price of the day
       */
      o?: number;
      /**
       * Format: float
       * @description High price of the day
       */
      h?: number;
      /**
       * Format: float
       * @description Low price of the day
       */
      l?: number;
      /**
       * Format: float
       * @description Current price. After the regular-session close, this holds the official close.
       */
      c?: number;
      /**
       * Format: float
       * @description Previous close price
       */
      pc?: number;
      /**
       * Format: float
       * @description Change
       */
      d?: number;
      /**
       * Format: float
       * @description Percent change
       */
      dp?: number;
      /**
       * Format: int64
       * @description Quote timestamp (UNIX seconds) of the last update. Present in the live response though absent from the upstream Swagger schema; retained here because the capture job uses it to confirm the quote belongs to the just-closed session.
       */
      t?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  quote: {
    parameters: {
      query: {
        /** @description Symbol. tickr passes its stored symbol as-is; Finnhub accepts both dotted and dashed class shares (e.g. BRK.B and BRK-B resolve identically). */
        symbol: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Quote'];
        };
      };
    };
  };
}
